package com.github.courtandrey.sudrfscraper.service;

public enum Constant {
    PATH_TO_APP_PROPERTIES,
    BASIC_RESULT_PATH ,
    PATH_TO_RESULT_DIRECTORY,
    PATH_TO_RESULT_JSON,
    PATH_TO_RESULT_CSV,
    CSV_HEADER,
    PATH_TO_RESULT_META,
    PATH_TO_SUMMARY,
    UA,
    PATH_TO_CONFIG,
    PATH_TO_CONFIG_BACKUP,
    PATH_TO_CONFIG_BASE,
    PATH_TO_CAPTCHA,
    PATH_TO_CAS_MOSGORSUD_LAWBOOK,
    PATH_TO_LOGS,
    PATH_TO_COURT_HISTORY,
    PATH_TO_SUMMARY_INFO,
    DB_Driver,
    PATH_TO_CRIMINAL_PROPERTIES,
    PATH_TO_ADMIN_PROPERTIES,
    PATH_TO_CAS_PROPERTIES,
    PATH_TO_TEMP, PATH_TO_MATERIAL_PROCEEDING_PROPERTIES, PATH_TO_UPK_LAWBOOK, PATH_TO_CIVIL_PROPERTIES;
    @Override
    public String toString() {
        return ConstantsGetter.getStringConstant(this);
    }
}
